# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=20)),
                ('account_id', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
